name: Metrics
on:
  # every day updat
  schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: vinograpsov
          template: classic
          
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Warsaw
          
#           plugin_topics: yes
#           plugin_topics_limit: 15
#           plugin_topics_mode: icons
#           plugin_topics_sort: stars
          
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
#           plugin_languages: yes
#           plugin_languages_ignored: html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell, gnuplot, jupyter notebook 
#           plugin_languages_details: percentage
             
          plugin_lines: yes
          plugin_lines_history_limit: 1
          # Years to display
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          

                    
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          
